In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

2- 7 sayfalardaki verileri çekiyor.

In [18]:
cities = [
    "adana", "adiyaman", "afyonkarahisar", "agri", "aksaray", "amasya", "ankara", "antalya",
    "ardahan", "artvin", "aydin", "balikesir", "bartin", "batman", "bayburt", "bilecik",
    "bingol", "bitlis", "bolu", "burdur", "bursa", "canakkale", "cankiri", "corum",
    "denizli", "diyarbakir", "duzce", "edirne", "elazig", "erzincan", "erzurum",
    "eskisehir", "gaziantep", "giresun", "gumushane", "hakkari", "hatay", "igdir",
    "isparta", "mersin", "istanbul", "izmir", "kahramanmaras", "karabuk", "karaman",
    "kars", "kastamonu", "kayseri", "kilis", "kirikkale", "kirklareli", "kirsehir",
    "kocaeli", "konya", "kutahya", "malatya", "manisa", "mardin", "mugla", "mus",
    "nevsehir", "nigde", "ordu", "osmaniye", "rize", "sakarya", "samsun", "sanliurfa",
    "siirt", "sinop", "sivas", "tekirdag", "tokat", "trabzon", "tunceli", "usak",
    "van", "yalova", "yozgat", "zonguldak", "sirnak"
]
cities_pages = {}

for city in cities:
    url = f"https://www.emlakjet.com/kiralik-konut/{city}"

    print(f"Sayfa {city} -> {url}")

    response = requests.get(url)
    soup = BeautifulSoup(response.content, "html.parser")

   
    page_numbers = []
    for li in soup.select("ul.styles_list__ExTZw li"):
        text = li.get_text(strip = True)
        if text.isdigit():
            page_numbers.append(int(text))

    if page_numbers:
        total_pages = max(page_numbers)
        print("toplam sayfa sayısı",total_pages)
    else:
        total_pages = 1
        print("Toplam sayfa sayısı",total_pages)

    cities_pages[city] = total_pages

print("\nTüm şehirlerin sayfa sayıları:")
print(cities_pages)

Sayfa adana -> https://www.emlakjet.com/kiralik-konut/adana
toplam sayfa sayısı 43
Sayfa adiyaman -> https://www.emlakjet.com/kiralik-konut/adiyaman
Toplam sayfa sayısı 1
Sayfa afyonkarahisar -> https://www.emlakjet.com/kiralik-konut/afyonkarahisar
toplam sayfa sayısı 6
Sayfa agri -> https://www.emlakjet.com/kiralik-konut/agri
Toplam sayfa sayısı 1
Sayfa aksaray -> https://www.emlakjet.com/kiralik-konut/aksaray
toplam sayfa sayısı 3
Sayfa amasya -> https://www.emlakjet.com/kiralik-konut/amasya
toplam sayfa sayısı 5
Sayfa ankara -> https://www.emlakjet.com/kiralik-konut/ankara
toplam sayfa sayısı 50
Sayfa antalya -> https://www.emlakjet.com/kiralik-konut/antalya
toplam sayfa sayısı 50
Sayfa ardahan -> https://www.emlakjet.com/kiralik-konut/ardahan
Toplam sayfa sayısı 1
Sayfa artvin -> https://www.emlakjet.com/kiralik-konut/artvin
Toplam sayfa sayısı 1
Sayfa aydin -> https://www.emlakjet.com/kiralik-konut/aydin
toplam sayfa sayısı 32
Sayfa balikesir -> https://www.emlakjet.com/kiralik-konut/balikesir
toplam sayfa sayısı 34
Sayfa bartin -> https://www.emlakjet.com/kiralik-konut/bartin
toplam sayfa sayısı 3
Sayfa batman -> https://www.emlakjet.com/kiralik-konut/batman
toplam sayfa sayısı 4
Sayfa bayburt -> https://www.emlakjet.com/kiralik-konut/bayburt
Toplam sayfa sayısı 1
Sayfa bilecik -> https://www.emlakjet.com/kiralik-konut/bilecik
toplam sayfa sayısı 2
Sayfa bingol -> https://www.emlakjet.com/kiralik-konut/bingol
Toplam sayfa sayısı 1
Sayfa bitlis -> https://www.emlakjet.com/kiralik-konut/bitlis
Toplam sayfa sayısı 1
Sayfa bolu -> https://www.emlakjet.com/kiralik-konut/bolu
toplam sayfa sayısı 2
Sayfa burdur -> https://www.emlakjet.com/kiralik-konut/burdur
toplam sayfa sayısı 4
Sayfa bursa -> https://www.emlakjet.com/kiralik-konut/bursa
toplam sayfa sayısı 49
Sayfa canakkale -> https://www.emlakjet.com/kiralik-konut/canakkale
toplam sayfa sayısı 9
Sayfa cankiri -> https://www.emlakjet.com/kiralik-konut/cankiri
Toplam sayfa sayısı 1
Sayfa corum -> https://www.emlakjet.com/kiralik-konut/corum
toplam sayfa sayısı 3
Sayfa denizli -> https://www.emlakjet.com/kiralik-konut/denizli
toplam sayfa sayısı 28
Sayfa diyarbakir -> https://www.emlakjet.com/kiralik-konut/diyarbakir
toplam sayfa sayısı 5
Sayfa duzce -> https://www.emlakjet.com/kiralik-konut/duzce
toplam sayfa sayısı 7
Sayfa edirne -> https://www.emlakjet.com/kiralik-konut/edirne
toplam sayfa sayısı 6
Sayfa elazig -> https://www.emlakjet.com/kiralik-konut/elazig
toplam sayfa sayısı 2
Sayfa erzincan -> https://www.emlakjet.com/kiralik-konut/erzincan
Toplam sayfa sayısı 1
Sayfa erzurum -> https://www.emlakjet.com/kiralik-konut/erzurum
toplam sayfa sayısı 5
Sayfa eskisehir -> https://www.emlakjet.com/kiralik-konut/eskisehir
toplam sayfa sayısı 26
Sayfa gaziantep -> https://www.emlakjet.com/kiralik-konut/gaziantep
toplam sayfa sayısı 13
Sayfa giresun -> https://www.emlakjet.com/kiralik-konut/giresun
toplam sayfa sayısı 5
Sayfa gumushane -> https://www.emlakjet.com/kiralik-konut/gumushane
Toplam sayfa sayısı 1
Sayfa hakkari -> https://www.emlakjet.com/kiralik-konut/hakkari
Toplam sayfa sayısı 1
Sayfa hatay -> https://www.emlakjet.com/kiralik-konut/hatay
toplam sayfa sayısı 4
Sayfa igdir -> https://www.emlakjet.com/kiralik-konut/igdir
Toplam sayfa sayısı 1
Sayfa isparta -> https://www.emlakjet.com/kiralik-konut/isparta
toplam sayfa sayısı 11
Sayfa mersin -> https://www.emlakjet.com/kiralik-konut/mersin
toplam sayfa sayısı 33
Sayfa istanbul -> https://www.emlakjet.com/kiralik-konut/istanbul
toplam sayfa sayısı 50
Sayfa izmir -> https://www.emlakjet.com/kiralik-konut/izmir
toplam sayfa sayısı 50
Sayfa kahramanmaras -> https://www.emlakjet.com/kiralik-konut/kahramanmaras
toplam sayfa sayısı 3
Sayfa karabuk -> https://www.emlakjet.com/kiralik-konut/karabuk
toplam sayfa sayısı 2
Sayfa karaman -> https://www.emlakjet.com/kiralik-konut/karaman
toplam sayfa sayısı 2
Sayfa kars -> https://www.emlakjet.com/kiralik-konut/kars
toplam sayfa sayısı 4
Sayfa kastamonu -> https://www.emlakjet.com/kiralik-konut/kastamonu
toplam sayfa sayısı 3
Sayfa kayseri -> https://www.emlakjet.com/kiralik-konut/kayseri
toplam sayfa sayısı 11
Sayfa kilis -> https://www.emlakjet.com/kiralik-konut/kilis
toplam sayfa sayısı 5
Sayfa kirikkale -> https://www.emlakjet.com/kiralik-konut/kirikkale
Toplam sayfa sayısı 1
Sayfa kirklareli -> https://www.emlakjet.com/kiralik-konut/kirklareli
toplam sayfa sayısı 7
Sayfa kirsehir -> https://www.emlakjet.com/kiralik-konut/kirsehir
Toplam sayfa sayısı 1
Sayfa kocaeli -> https://www.emlakjet.com/kiralik-konut/kocaeli
toplam sayfa sayısı 27
Sayfa konya -> https://www.emlakjet.com/kiralik-konut/konya
toplam sayfa sayısı 10
Sayfa kutahya -> https://www.emlakjet.com/kiralik-konut/kutahya
toplam sayfa sayısı 4
Sayfa malatya -> https://www.emlakjet.com/kiralik-konut/malatya
toplam sayfa sayısı 3
Sayfa manisa -> https://www.emlakjet.com/kiralik-konut/manisa
toplam sayfa sayısı 21
Sayfa mardin -> https://www.emlakjet.com/kiralik-konut/mardin
toplam sayfa sayısı 5
Sayfa mugla -> https://www.emlakjet.com/kiralik-konut/mugla
toplam sayfa sayısı 50
Sayfa mus -> https://www.emlakjet.com/kiralik-konut/mus
Toplam sayfa sayısı 1
Sayfa nevsehir -> https://www.emlakjet.com/kiralik-konut/nevsehir
toplam sayfa sayısı 2
Sayfa nigde -> https://www.emlakjet.com/kiralik-konut/nigde
toplam sayfa sayısı 3
Sayfa ordu -> https://www.emlakjet.com/kiralik-konut/ordu
toplam sayfa sayısı 13
Sayfa osmaniye -> https://www.emlakjet.com/kiralik-konut/osmaniye
toplam sayfa sayısı 2
Sayfa rize -> https://www.emlakjet.com/kiralik-konut/rize
toplam sayfa sayısı 2
Sayfa sakarya -> https://www.emlakjet.com/kiralik-konut/sakarya
toplam sayfa sayısı 21
Sayfa samsun -> https://www.emlakjet.com/kiralik-konut/samsun
toplam sayfa sayısı 35
Sayfa sanliurfa -> https://www.emlakjet.com/kiralik-konut/sanliurfa
toplam sayfa sayısı 16
Sayfa siirt -> https://www.emlakjet.com/kiralik-konut/siirt
Toplam sayfa sayısı 1
Sayfa sinop -> https://www.emlakjet.com/kiralik-konut/sinop
Toplam sayfa sayısı 1
Sayfa sivas -> https://www.emlakjet.com/kiralik-konut/sivas
toplam sayfa sayısı 4
Sayfa tekirdag -> https://www.emlakjet.com/kiralik-konut/tekirdag
toplam sayfa sayısı 27
Sayfa tokat -> https://www.emlakjet.com/kiralik-konut/tokat
toplam sayfa sayısı 4
Sayfa trabzon -> https://www.emlakjet.com/kiralik-konut/trabzon
toplam sayfa sayısı 12
Sayfa tunceli -> https://www.emlakjet.com/kiralik-konut/tunceli
Toplam sayfa sayısı 1
Sayfa usak -> https://www.emlakjet.com/kiralik-konut/usak
toplam sayfa sayısı 2
Sayfa van -> https://www.emlakjet.com/kiralik-konut/van
toplam sayfa sayısı 5
Sayfa yalova -> https://www.emlakjet.com/kiralik-konut/yalova
toplam sayfa sayısı 7
Sayfa yozgat -> https://www.emlakjet.com/kiralik-konut/yozgat
toplam sayfa sayısı 5
Sayfa zonguldak -> https://www.emlakjet.com/kiralik-konut/zonguldak
toplam sayfa sayısı 3
Sayfa sirnak -> https://www.emlakjet.com/kiralik-konut/sirnak
Toplam sayfa sayısı 1

Tüm şehirlerin sayfa sayıları:
{'adana': 43, 'adiyaman': 1, 'afyonkarahisar': 6, 'agri': 1, 'aksaray': 3, 'amasya': 5, 'ankara': 50, 'antalya': 50, 'ardahan': 1, 'artvin': 1, 'aydin': 32, 'balikesir': 34, 'bartin': 3, 'batman': 4, 'bayburt': 1, 'bilecik': 2, 'bingol': 1, 'bitlis': 1, 'bolu': 2, 'burdur': 4, 'bursa': 49, 'canakkale': 9, 'cankiri': 1, 'corum': 3, 'denizli': 28, 'diyarbakir': 5, 'duzce': 7, 'edirne': 6, 'elazig': 2, 'erzincan': 1, 'erzurum': 5, 'eskisehir': 26, 'gaziantep': 13, 'giresun': 5, 'gumushane': 1, 'hakkari': 1, 'hatay': 4, 'igdir': 1, 'isparta': 11, 'mersin': 33, 'istanbul': 50, 'izmir': 50, 'kahramanmaras': 3, 'karabuk': 2, 'karaman': 2, 'kars': 4, 'kastamonu': 3, 'kayseri': 11, 'kilis': 5, 'kirikkale': 1, 'kirklareli': 7, 'kirsehir': 1, 'kocaeli': 27, 'konya': 10, 'kutahya': 4, 'malatya': 3, 'manisa': 21, 'mardin': 5, 'mugla': 50, 'mus': 1, 'nevsehir': 2, 'nigde': 3, 'ordu': 13, 'osmaniye': 2, 'rize': 2, 'sakarya': 21, 'samsun': 35, 'sanliurfa': 16, 'siirt': 1, 'sinop': 1, 'sivas': 4, 'tekirdag': 27, 'tokat': 4, 'trabzon': 12, 'tunceli': 1, 'usak': 2, 'van': 5, 'yalova': 7, 'yozgat': 5, 'zonguldak': 3, 'sirnak': 1}

In [ ]:
page = 2
cities = [
    "adana", "adiyaman", "afyonkarahisar", "agri", "aksaray", "amasya", "ankara", "antalya",
    "ardahan", "artvin", "aydin", "balikesir", "bartin", "batman", "bayburt", "bilecik",
    "bingol", "bitlis", "bolu", "burdur", "bursa", "canakkale", "cankiri", "corum",
    "denizli", "diyarbakir", "duzce", "edirne", "elazig", "erzincan", "erzurum",
    "eskisehir", "gaziantep", "giresun", "gumushane", "hakkari", "hatay", "igdir",
    "isparta", "mersin", "istanbul", "izmir", "kahramanmaras", "karabuk", "karaman",
    "kars", "kastamonu", "kayseri", "kilis", "kirikkale", "kirklareli", "kirsehir",
    "kocaeli", "konya", "kutahya", "malatya", "manisa", "mardin", "mugla", "mus",
    "nevsehir", "nigde", "ordu", "osmaniye", "rize", "sakarya", "samsun", "sanliurfa",
    "siirt", "sinop", "sivas", "tekirdag", "tokat", "trabzon", "tunceli", "usak",
    "van", "yalova", "yozgat", "zonguldak", "sirnak"
]

all_data = []

def data_scraping(tag:str,attr_value:str) -> np.array:
    data_list = []
    data = soup.find_all(f"{tag}", class_ = f"{attr_value}")
    for i in data:
        data_list.append(i.get_text())
    return data_list


while page < 51:
    url = f"https://www.emlakjet.com/kiralik-daire/{cities[i]}?sayfa={page}"
    print(f"Sayfa {page} -> {url}")

    response = requests.get(url)
    soup = BeautifulSoup(response.content, "html")

    
    a = soup.find_all("div", attrs= {"styles_listingWrapper__I0H_l"})
    
    if not a: # veri gelmediyse duracak
        break


    locations = data_scraping("span", "styles_location__ieVpH")
    informations = data_scraping("div", "styles_quickinfoWrapper__F5BBD")
    sales_prices = data_scraping("div", "styles_priceContent__TBOLV")
    
    # her sayfayı ekler
    for loc, info, price in zip(locations, informations, sales_prices):
        all_data.append({
        "location": loc,
        "information": info,
        "sales_price": price
    })
        
    page += 1


df1 = pd.DataFrame(all_data)
df1.head()

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   location     1470 non-null   object
 1   information  1470 non-null   object
 2   sales_price  1470 non-null   object
dtypes: object(3)
memory usage: 34.6+ KB

ilk sayfa eksikti onuda çektim

In [ ]:
page1_data = []
url = f"https://www.emlakjet.com/kiralik-daire"
response = requests.get(url)
soup = BeautifulSoup(response.content, "html")

a = soup.find_all("div", attrs= {"styles_listingWrapper__I0H_l"})

locations = data_scraping("span", "styles_location__ieVpH")
informations = data_scraping("div", "styles_quickinfoWrapper__F5BBD")
sales_prices = data_scraping("div", "styles_priceContent__TBOLV")

# her sayfayı ekler
for loc, info, price in zip(locations, informations, sales_prices):
    page1_data.append({
    "location": loc,
    "information": info,
    "sales_price": price
})
df2 = pd.DataFrame(page1_data)
df2.head()

                  location                     information sales_price
0        İstanbul - Pendik   Daire | 3+1 | 4. Kat | 115 m²   29.000 TL
1  İstanbul - Bahçelievler   Daire | 3+1 | 1. Kat | 160 m²   55.000 TL
2          Adana - Sarıçam    Daire | 1+1 | 2. Kat | 60 m²    9.000 TL
3          Bursa - Nilüfer    Daire | 2+1 | 3. Kat | 92 m²   19.500 TL
4      Kayseri - Melikgazi  Daire | 3+1 | 11. Kat | 220 m²   19.500 TL

In [16]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   location     30 non-null     object
 1   information  30 non-null     object
 2   sales_price  30 non-null     object
dtypes: object(3)
memory usage: 852.0+ bytes

In [17]:
df = pd.concat([df1, df2], ignore_index= True)
df

,location,information,sales_price
0,İstanbul - Beyoğlu,Daire | 1+1 | 4. Kat | 70 m²,17.000 TL
1,Ankara - Çankaya,Daire | 1 Oda | 3. Kat | 45 m²,25.000 TL29.000 TL
2,Samsun - Atakum,Daire | 2+1 | 3. Kat | 110 m²,23.000 TL
3,İzmir - Buca,Daire | 2+0 | 2. Kat | 75 m²,15.000 TL
4,İstanbul - Arnavutköy,Daire | 1+1 | 4. Kat | 70 m²,16.000 TL
...,...,...,...
1495,İstanbul - Küçükçekmece,Daire | 3+1 | 8. Kat | 147 m²,50.500 TL
1496,Kocaeli - İzmit,Daire | 2+1 | Yüksek giriş | 77 m²,23.000 TL25.000 TL
1497,İstanbul - Esenyurt,Daire | 2+1 | 3. Kat | 110 m²,15.000 TL
1498,İstanbul - Esenyurt,Daire | 3+1 | 3. Kat | 128 m²,25.000 TL
1499,Antalya - Finike,Daire | 4+1 | 5. Kat | 170 m²,37.000 TL

In [12]:
df.head()

                location                     information         sales_price
0     İstanbul - Beyoğlu    Daire | 1+1 | 4. Kat | 70 m²           17.000 TL
1       Ankara - Çankaya  Daire | 1 Oda | 3. Kat | 45 m²  25.000 TL29.000 TL
2        Samsun - Atakum   Daire | 2+1 | 3. Kat | 110 m²           23.000 TL
3           İzmir - Buca    Daire | 2+0 | 2. Kat | 75 m²           15.000 TL
4  İstanbul - Arnavutköy    Daire | 1+1 | 4. Kat | 70 m²           16.000 TL

verileri csv dosyası olarak sakladım

In [19]:
df.to_csv("turkiye_kiralik_daireler.csv", index=False, encoding="utf-8")